=== stIncMale/pies/pies-app/pies-app-echo/pies-app-echo-logic/src/config/echoConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="config"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="urn:com:gl:vn:me:ko:pies:app:echo:application"
		   xmlns="urn:com:gl:vn:me:ko:pies:app:echo:application"
		   attributeFormDefault="qualified"
		   elementFormDefault="qualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:all>
				<xs:element name="echoServer" type="inetServer"/>
				<xs:element name="controlServer" type="controlServer"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="inetAddress">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="port">
		<xs:restriction base="xs:unsignedShort"/>
	</xs:simpleType>
	<xs:complexType name="inetServerSocket">
		<xs:all>
			<xs:element name="host" type="inetAddress" minOccurs="0"/>
			<xs:element name="port" type="port"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="inetServerThreads">
		<xs:all>
			<xs:element name="acceptors" type="xs:int"/>
			<xs:element name="workers" type="xs:int"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="controlServerThreads">
		<xs:all>
			<xs:element name="acceptors" type="xs:int"/>
			<xs:element name="workers" type="xs:int"/>
			<xs:element name="postResponseWorkers" type="xs:int"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="inetServer">
		<xs:all>
			<xs:element name="socket" type="inetServerSocket"/>
			<xs:element name="threads" type="inetServerThreads"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="controlServer">
		<xs:all>
			<xs:element name="socket" type="inetServerSocket"/>
			<xs:element name="threads" type="controlServerThreads"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== stIncMale/pies/pies-app/pies-app-echo/pies-app-echo-logic/src/config/echoConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file represents config of the PIES Echo Application.
Properties MUST be considered mandatory unless otherwise is specified.
-->
<config
	xmlns="urn:com:gl:vn:me:ko:pies:app:echo:application"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:com:gl:vn:me:ko:pies:app:echo:application echoConfig.xsd">
	<echoServer>
		<socket>
			<!--
			Internet address of a network interface the server uses to listen for echo requests.
			Optional property. If the property isn't specified the value is determined automatically.
			-->
			<host>localhost</host>
			<!--
			TCP port the server listens for echo requests.
			-->
			<port>7000</port>
		</socket>
		<threads>
			<!--
			Maximum number of threads that accept new TCP connections.
			-->
			<acceptors>2</acceptors>
			<!--
			Maximum number of threads that process data received via the accepted TCP connections.
			-->
			<workers>3</workers>
		</threads>
	</echoServer>
	<controlServer>
		<socket>
			<!--
			Internet address of a network interface the server uses to listen for control requests (REST).
			Optional property. If the property isn't specified the value is determined automatically.
			-->
			<host>localhost</host>
			<!--
			TCP port the server listens for control requests.
			-->
			<port>5202</port>
		</socket>
		<threads>
			<!--
			Maximum number of threads that accept new TCP connections.
			-->
			<acceptors>2</acceptors>
			<!--
			Maximum number of threads that process data received via the accepted TCP connections.
			-->
			<workers>3</workers>
			<!--
			Maximum number of threads that perform post-response actions
			(actions that are performed after sending an HTTP response).
			-->
			<postResponseWorkers>1</postResponseWorkers>
		</threads>
	</controlServer>
</config>
