=== stIncMale/pies/pies-base/pies-base-config/src/test/resources/com/gl/vn/me/ko/pies/base/config/testXmlConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="test"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:com:gl:vn:me:ko:pies"
	xmlns="urn:com:gl:vn:me:ko:pies"
	attributeFormDefault="qualified"
	elementFormDefault="qualified">
	<xs:element name="someRootElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="foo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bar">
								<xs:complexType>
									<xs:all>
										<xs:element name="testString" type="xs:string"
											fixed="value 𤧰 &#x0064;&#x494F8;"/>
										<xs:element name="testMultipleOfStrings" type="xs:string"/>
										<xs:element name="testInteger" type="xs:integer" fixed="-1"/>
										<xs:element name="testLong" type="xs:long" fixed="9000000000"/>
										<xs:element name="testDouble" type="xs:double" fixed="1.6E10"/>
										<xs:element name="testBooleanTrue" type="xs:boolean" fixed="true"/>
										<xs:element name="testBooleanFalse" type="xs:boolean" fixed="false"/>
										<xs:element name="testBigInteger" type="xs:string" fixed="999999999999999999"/>
										<xs:element name="testBigDecimal" type="xs:string" fixed="-0.5E-9999"/>
										<xs:element name="testVariableInterpolation" type="xs:string"/>
										<xs:element name="testStringable" type="xs:string" fixed="a"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== stIncMale/pies/pies-base/pies-base-config/src/test/resources/com/gl/vn/me/ko/pies/base/config/testXmlConfigValid.xml
<?xml version="1.0" encoding="UTF-8"?>
<someRootElement
	xmlns="urn:com:gl:vn:me:ko:pies"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:com:gl:vn:me:ko:pies testXmlConfig.xsd">
	<foo>
		<bar>
			<testString>value ð¤§° &#x0064;&#x494F8;</testString>
			<testMultipleOfStrings>value1; value2;
				value1;
				value3;
				valueWithEscaped\;Semicolon
			</testMultipleOfStrings>
			<testInteger>-1</testInteger>
			<testLong>9000000000</testLong>
			<testDouble>1.6E10</testDouble>
			<testBooleanTrue>true</testBooleanTrue>
			<testBooleanFalse>false</testBooleanFalse>
			<testBigInteger>999999999999999999</testBigInteger>
			<testVariableInterpolation>${foo.bar.testBigDecimal}</testVariableInterpolation>
			<testBigDecimal>-0.5E-9999</testBigDecimal>
			<testStringable>a</testStringable>
		</bar>
	</foo>
</someRootElement>

=== stIncMale/pies/pies-base/pies-base-config/src/test/resources/com/gl/vn/me/ko/pies/base/config/testXmlConfigInvalid2.xml
<?xml version="1.0" encoding="UTF-8"?>
<someRootElement
	xmlns="urn:com:gl:vn:me:ko:pies"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:com:gl:vn:me:ko:pies testXmlConfig.xsd">
	<foo>
		<bar>
			<testString>value</testString>
			<testMultipleOfStrings>value1; value2;
				value1;
				value3;
				valueWithEscaped\;Semicolon
			</testMultipleOfStrings>
			<testInteger>-1</testInteger>
			<testLong>9000000000</testLong>
			<testDouble>_1.6E10</testDouble><!-- invalid content -->
			<testBoolean>true</testBoolean>
			<testBigInteger>999999999999999999</testBigInteger>
			<testBigDecimal>-0.5E-9999</testBigDecimal>
		</bar>
	</foo>
</someRootElement>
